config/routes.rb
Guestlist::Application.routes.draw do

  match 'guests/priority/:id', :to => "guests#priority",:as => :priority

  resources :memberships

  resources :groups

  resources :guests do
    collection do
      get 'sponsors', :as => :sponsors
    end
  end

  root :to => "guests#index"

end

app/models/group.rb
class Group < ActiveRecord::Base  
  has_many :memberships, :dependent => :destroy
  has_many :guests, :through => :memberships
  
  def self.show_all(group)
    self.find_by_name(group).guests.collect{ |x| x.name  }
  end
end

app/models/guest.rb
class Guest < ActiveRecord::Base
  has_many :memberships, :dependent => :destroy
  has_many :groups, :through => :memberships
  
  scope :sponsors, where("is_sponsor IS true")
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :guest
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(params[:group])
    if @group.save
      redirect_to @group, :notice => "Successfully created group."
    else
      render :action => 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update_attributes(params[:group])
      redirect_to @group, :notice  => "Successfully updated group."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_url, :notice => "Successfully destroyed group."
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def index
    @guests = Guest.all
  end

  def show
    @guest = Guest.find(params[:id])
  end

  def new
    @guest = Guest.new
  end

  def create
    @guest = Guest.new(params[:guest])
    if @guest.save
      redirect_to @guest, :notice => "Successfully created guest."
    else
      render :action => 'new'
    end
  end

  def priority
    @guests = Guest.find_all_by_priority(params[:id])
  end

  def edit
    @guest = Guest.find(params[:id])
  end

  def update
    @guest = Guest.find(params[:id])
    @guest.attributes = {'group_ids' => []}.merge(params[:guest] || {})

    if @guest.update_attributes(params[:guest])
      redirect_to guests_url, :notice  => "Successfully updated guest."
    else
      render :action => 'edit'
    end
  end

  def sponsors
    @guests = Guest.sponsors
  end

  def destroy
    @guest = Guest.find(params[:id])
    @guest.destroy
    redirect_to guests_url, :notice => "Successfully destroyed guest."
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def index
    @memberships = Membership.all
  end

  def show
    @membership = Membership.find(params[:id])
  end

  def new
    @membership = Membership.new
  end

  def create
    @membership = Membership.new(params[:membership])
    if @membership.save
      redirect_to @membership, :notice => "Successfully created membership."
    else
      render :action => 'new'
    end
  end

  def edit
    @membership = Membership.find(params[:id])
  end

  def update
    @membership = Membership.find(params[:id])
    if @membership.update_attributes(params[:membership])
      redirect_to @membership, :notice  => "Successfully updated membership."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy
    redirect_to memberships_url, :notice => "Successfully destroyed membership."
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/memberships_helper.rb
module MembershipsHelper
end

app/views/groups/_form.html.haml
= form_for @group do |f|
  = f.error_messages
  %p
    = f.label :name
    %br
    = f.text_field :name
  %p
    = f.submit

app/views/groups/edit.html.haml
- title "Edit Group"

= render 'form'

%p
  = link_to "Show", group
  |
  = link_to "View All", groups_path

app/views/groups/index.html.haml
- title "Groups"

%table
  %tr
    %th Name
    %th{:colspan => 2} &nbsp;
  - for group in @groups
    %tr{:class => cycle("even","odd")}
      %td= group.name
      %td= link_to 'Edit', edit_group_path(group)
      %td= link_to 'Destroy', group, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Group", new_group_path

app/views/groups/new.html.haml
- title "New Group"

= render 'form'

%p= link_to "Back to List", groups_path

app/views/groups/show.html.haml
- title "Group"

%p
  %strong Name:
  = @group.name

%p
  = link_to "Edit", edit_group_path(@group)
  |
  = link_to "Destroy", @group, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", groups_path

app/views/guests/_form.html.haml
%fieldset
  = form_for @guest do |f|
    = f.error_messages
    %ul
      %li
        = f.label :name
        = f.text_field :name
      %li
        = f.label :address
        = f.text_field :address
      %li
        = f.label :side
        = f.text_field :side
      %li
        = f.label :is_adult
        = f.check_box :is_adult
      %li
        = f.label :status
        = f.check_box :status
      %li
        = f.label :priority
        = f.select :priority, "<option value='1'>High</option><option value='2'>Medium</option><option value='3'>Low</option>"
      %li
        = f.label :accomodation, "Needs Accommodation?"
        = f.check_box :accomodation
      %li
        = f.label :transportation, "Needs Transportation?"
        = f.check_box :transportation
      %li
        = f.label :sent_std, "Was sent STD?"
        = f.check_box :sent_std
      %li
        = f.label :sent_invitation, "Was sent invitation?"
        = f.check_box :sent_invitation
      %li
        = f.label :is_sponsor, "Is a sponsor?"
        = f.check_box :is_sponsor
      %li
        = f.label :sponsor_type, "Sponsor Type"
        = f.select(:sponsor_type, options_for_select(["Principal", "Veil", "Candle", "Cord", "Flower Girl", "Groomsman", "Bridesmaid", "Bearer"], :selected => @guest.sponsor_type ? @guest.sponsor_type : nil), :prompt => "Select a type")
      %li
        %ul
        - Group.all.each do |group|
          %li
            = check_box_tag :group_ids, group.id, @guest.groups.include?(group), :name => 'guest[group_ids][]'
            = label_tag :group_ids, group.name

      %li
        = f.submit

app/views/guests/_list.html.haml
%table.tablesorter
  %thead
    %tr
      %th &nbsp;
      %th Name
      %th Address
      %th Side
      %th Is adult
      %th Status
      %th Priority
      %th Groups
      %th Sent STD
      %th{:colspan => 2} &nbsp;
  %tbody
    - guests.each_with_index do |guest, index|
      %tr
        %td= index
        %td= guest.name
        %td= guest.address
        %td= guest.side
        %td= guest.is_adult
        %td= guest.status
        %td= guest.priority
        %td= guest.groups.collect{ |x| "#{x.name}" }.join(", ") if guest.groups
        %td{:class => guest.sent_std.to_s }= guest.sent_std
        %td= link_to 'Edit', edit_guest_path(guest)
        %td= link_to 'Delete', guest, :confirm => 'Are you sure?', :method => :delete

app/views/guests/edit.html.haml
- title "Edit Guest"

= render 'form'

%p
  = link_to "Show", @guest
  |
  = link_to "View All", guests_path

app/views/guests/index.html.haml
- title "Guests"

%h2 Statistics:

%ul
  %li= link_to "High Priority Count: #{Guest.find_all_by_priority(1).size}", priority_path(1)
  %li= link_to "Medium Priority Count: #{Guest.find_all_by_priority(2).size}", priority_path(2)
  %li= link_to "Low Priority Count: #{Guest.find_all_by_priority(3).size}", priority_path(3)
  %li= "Family Count: #{Group.show_all('Family').size}"
  %li= "Friend Count: #{Group.show_all('Friends').size}"
  %li= "Children Count: #{Guest.find_all_by_is_adult(false).size}"
  %li= "Total Count(ALL) #{@guests.size}"

%p= link_to "Sponsors", sponsors_guests_path

= render :partial => "list", :locals => {:guests => @guests}

%p= link_to "New Guest", new_guest_path

app/views/guests/new.html.haml
- title "New Guest"

= render 'form'

%p= link_to "Back to List", guests_path

app/views/guests/priority.html.haml
%p= link_to "Back to main list", guests_path

%h1 Sponsors

= render :partial => "list", :locals => {:guests => @guests}

app/views/guests/show.html.haml
- title "Guest"

%p
  %strong Name:
  = @guest.name
%p
  %strong Address:
  = @guest.address
%p
  %strong Side:
  = @guest.side
%p
  %strong Is Adult:
  = @guest.is_adult
%p
  %strong Status:
  = @guest.status
  
%p
  %strong Priority:
  = @guest.priority if @guest.priority

- if @guest.groups
  
  %p
    %strong Groups:
    = @guest.groups.map{ |x| x.name }.join(", ")

%p
  = link_to "Edit", edit_guest_path(@guest)
  |
  = link_to "Destroy", @guest, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", guests_path

app/views/guests/sponsors.haml
%h1 Sponsors

%table.tablesorter
  %thead
    %tr
      %th &nbsp;
      %th Name
      %th Address
      %th Side
      %th Is adult
      %th Status
      %th Priority
      %th Groups
      %th Sent STD
      %th Sponsor Type
      %th{:colspan => 2} &nbsp;
  %tbody
    - @guests.each_with_index do |guest, index|
      %tr
        %td= index
        %td= guest.name
        %td= guest.address
        %td= guest.side
        %td= guest.is_adult
        %td= guest.status
        %td= guest.priority
        %td= guest.groups.collect{ |x| "#{x.name}" }.join(", ") if guest.groups
        %td{:class => guest.sent_std.to_s }= guest.sent_std
        %td= guest.sponsor_type
        %td= link_to 'Edit', edit_guest_path(guest)
        %td= link_to 'Delete', guest, :confirm => 'Are you sure?', :method => :delete

app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    %link{:href => "/stylesheets/compiled/main.css", :media => "screen, projection", :rel => "stylesheet", :type => "text/css"}/
    %link{:href => "/stylesheets/compiled/print.css", :media => "print", :rel => "stylesheet", :type => "text/css"}/
    /[if IE]
      <link href="/stylesheets/compiled/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
    = javascript_include_tag :defaults
    = javascript_include_tag 'jquery.tablesorter'
    = csrf_meta_tag
    = yield(:head)

  %body.bp
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

      = yield

app/views/memberships/_form.html.haml
= form_for @membership do |f|
  = f.error_messages
  %p
    = f.label :guest_id
    %br
    = f.text_field :guest_id
  %p
    = f.label :group_id
    %br
    = f.text_field :group_id
  %p
    = f.submit

app/views/memberships/edit.html.haml
- title "Edit Membership"

= render 'form'

%p
  = link_to "Show", membership
  |
  = link_to "View All", memberships_path

app/views/memberships/index.html.haml
- title "Memberships"

%table
  %tr
    %th Guest
    %th Group
  - for membership in @memberships
    %tr
      %td= membership.guest_id
      %td= membership.group_id
      %td= link_to 'Show', membership
      %td= link_to 'Edit', edit_membership_path(membership)
      %td= link_to 'Destroy', membership, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Membership", new_membership_path

app/views/memberships/new.html.haml
- title "New Membership"

= render 'form'

%p= link_to "Back to List", memberships_path

app/views/memberships/show.html.haml
- title "Membership"

%p
  %strong Guest:
  = @membership.guest_id
%p
  %strong Group:
  = @membership.group_id

%p
  = link_to "Edit", edit_membership_path(@membership)
  |
  = link_to "Destroy", @membership, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", memberships_path